  name: Deploy Frontend
  on:
    push:
      branches:
        - master

  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Build project
          run: |
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            docker build -t eduardbatiushchenko/docker-react -f Dockerfile.dev .
        - name: Run tests
          run:  docker run -e CI=true eduardbatiushchenko/docker-react npm run test -- --coverage

